apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: podinfo.bigbang.dev
spec:
  namespace: podinfo
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: podinfo.bigbang.dev
  namespace: podinfo
spec:
  ref:
    name: podinfo
    kind: Service
    apiVersion: serving.knative.dev/v1
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: podinfo
  namespace: podinfo
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: stefanprodan/podinfo
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: TARGET
          value: World
        image: stefanprodan/podinfo
        name: ""
        ports:
        - containerPort: 9898
        resources: {}
status: {}