apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          app: public-ingressgateway
  config:
    istio:
      gateway.istio-system.public: public-ingressgateway.istio-system.svc.cluster.local
    domain:
      bigbang.dev: |
        bigbang.dev: |
